name: felixfund
description: A personalized budget-tracking app for personal use on Android.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version information
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3

  # State management
  provider: ^6.0.5

  # UI
  cupertino_icons: ^1.0.5
  fl_chart: ^0.63.0
  intl: ^0.18.1

  # Security
  flutter_secure_storage: ^8.0.0

  # Google integration for backup
  google_sign_in: ^6.1.4
  googleapis: ^11.2.0
  http: ^1.1.0

  # File handling
  file_picker: ^5.3.2

  # Local storage
  shared_preferences: ^2.1.2

  # Permissions
  permission_handler: ^10.4.0

  # Biometric auth (optional)
  local_auth: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#1B263B"  # Deep Navy Blue
  adaptive_icon_foreground: "assets/images/app_logo_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700